[package]
name = "aoc_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "a01a"
src = "src/bin/a01a.rs"

[[bin]]
name = "a01b"
src = "src/bin/a01b.rs"



[dependencies]
